build:
  publish: public
  environment:
    HUGO_VERSION: 0.83.1
context:
  production:
    command: npm run build
  deploy-preview:
    command: npm run build
  branch-deploy:
    command: npm run build
